#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Hasklug Nerd Font:Bold:12.0"
yabai -m config status_bar_icon_font         "Hasklug Nerd Font:Bold:12.0" yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6 
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        " "

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      exterior 
yabai -m config window_border_width          0
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# Space labels
yabai -m space 1 --label "Browsing"
yabai -m space 2 --label "Development"
yabai -m space 3 --label "Social"
yabai -m space 4 --label "Media"
yabai -m space 5 --label "Tools"

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5

# rules for apps
# unmanaged
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Preview$" manage=off border=off
yabai -m rule --add app="^KeePassXC$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Home$" manage=off
yabai -m rule --add app="^TextEdit$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Shadow$" manage=off

# browsing - 1
yabai -m rule --add app="^Firefox$" space=^1
yabai -m rule --add app="^Safari$" space=^1
yabai -m rule --add app="^Firefox Nightly$" space=^1
yabai -m rule --add app="^Tor Browser$" space=^1

# development - 2 
yabai -m rule --add app="^Alacritty$" space=^2

# social - 3
yabai -m rule --add app="^zoom.us$" space=^3 manage=off
yabai -m rule --add app="^Messages$" space=^3
yabai -m rule --add app="^FaceTime$" space=^3 manage=off
yabai -m rule --add app="^Slack$" space=^3
yabai -m rule --add app="^Mail$" space=^3
yabai -m rule --add app="^Discord$" space=^3 manage=off

# music / notes / photos - 4
yabai -m rule --add app="^Notes$" space=^4
yabai -m rule --add app="^Music$" space=^4
yabai -m rule --add app="^Spotify$" space=^4
yabai -m rule --add app="^Photos$" space=^4

# tools - 5
yabai -m rule --add app="^Arq$" space=^5
yabai -m rule --add app="^App Store$" space=^5 manage=off
yabai -m rule --add app="^Docker$" space=^5 manage=off
yabai -m rule --add app="^Postgres$" space=^5 manage=off
